# Generated by Django 2.0.9 on 2018-12-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
