# Generated by Django 2.0.9 on 2019-01-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Language'),
        ),
    ]
