# Generated by Django 2.0.9 on 2019-03-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='unique_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
