# Generated by Django 2.0.9 on 2019-01-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190112_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'verbose_name': 'verse', 'verbose_name_plural': 'Verse'},
        ),
        migrations.AlterField(
            model_name='book',
            name='total_chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_verses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='total_verses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
