# Generated by Django 2.0.9 on 2019-01-12 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20190112_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Language'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_chapters',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_verses',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='total_verses',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='description',
        ),
    ]
